version: '3.8'
services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    env_file:
      - ./frontend/.env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - postgres
    env_file:
      - ./backend/.env

  postgres:
    image: 'postgres:15'
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env

  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '8090:81'
    volumes:
      - ./proxy/data:/data
      - ./proxy/letsencrypt:/etc/letsencrypt

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./proxy_params.conf:/etc/nginx/proxy_params.conf
      - ./nginx/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
      - postgres
      - adminer 
      - proxy
